spring:
  profiles: container
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERYSERVICE_URI}
management:
  security:
    enabled: false