spring:
  profiles: container
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASESERVER_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERYSERVICE_URI}
blogService:
  url: ${BLOGSERVER_URI}
authService:
  url: ${AUTHSERVER_URI}
socialService:
  url: ${SOCIALSERVER_URI}
  
upload:
  path: ${UPLOAD_PATH}
separator:
  ds: /
  oppositeDS: \\
fileUploadValidatorMsg: Please select a file!

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${OAUTH2CLIENTID}
      clientSecret: ${OAUTH2CLIENTSECRET}
      scope:
        ${OAUTH2CLIENTSCOPE}
      accessTokenUri: http://localhost:8100/oauth/token
      userAuthorizationUri: http://localhost:8100/oauth/authorize
    resource:
      userInfoUri: http://localhost:8100/api/user