spring:
  profiles: umax
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elevysic_socialdb
    username: admin
    password: fShZLLvaSPRr955u
    
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://23.95.0.172:8761/eureka/
blogService:
  url: http://blog.notebyelvis.com
authService:
  url: http://auth.notebyelvis.com
socialService:
  url: http://social.notebyelvis.com
  
upload:
  path: /var/www/html/media/Uploads/images/
  mean: /var/www/html/media/Uploads/images/
  meanFormatted: /var/www/html/media/Uploads/images/
separator:
  ds: /
  oppositeDS: \\
fileUploadValidatorMsg: Please select a file!

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SocialApp
      clientSecret: Fields2018
      scope:
        read
      accessTokenUri: http://auth.notebyelvis.com/oauth/token
      userAuthorizationUri: http://auth.notebyelvis.com/oauth/authorize
    resource:
      userInfoUri: http://auth.notebyelvis.com/api/user