spring:
  profiles: container
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: ${EUREKASERVER_URI}
  server:
    waitTimeInMsWhenSyncEmpty: 5
    peer-node-read-timeout-ms: 10000
    
