spring:
  profiles: default
  session:
    cookie:
      name: ELAUTHSESSION
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/elevysic_auth
    username: elevysi
    password: root
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
signing:
    key: 1234Elevysi

blogService:
  url: http://localhost:8400
authService:
  url: http://localhost:8100
socialService:
  url: http://localhost:8200
upload:
  path: ${UPLOAD_PATH}
separator:
  ds: /
  oppositeDS: \\
fileUploadValidatorMsg: Please select a file!
security:
  oauth2:
    client:
      clientId: AuthApp
      clientSecret: Fields2019
      scope: read
      accessTokenUri: http://localhost:8100/oauth/token
      userAuthorizationUri: http://localhost:8100/oauth/authorize
    resource:
      userInfoUri: http://localhost:8100/api/user